package by.epam.project.command;

/**
 * Constants for receiving and sending requests
 */

public class RequestAttribute {
    public static final String LOCK = "lock";
    public static final String EMAIL = "email";
    public static final String LIST_FILMS = "films";
    public static final String CURRENT_FILM_PAGE = "currentFilmPage";
    public static final String CURRENT_TABLE_FILM_PAGE = "currentTableFilmPage";
    public static final String FILMS_ON_PAGE = "filmsOnPage";
    public static final String FILMS_ON_PAGE_FILM_TABLE = "filmsOnPageFilmTable";
    public static final String NUMBER_OF_PAGES = "noOfPages";
    public static final String NUMBER_OF_PAGES_FILM_TABLE = "noOfPagesFilmTable";
    public static final String NUMBER_OF_PAGES_USER_TABLE = "noOfPagesUserTable";
    public static final String NUMBER_OF_PAGES_ADMIN_TABLE = "noOfPagesAdminTable";
    public static final String NUMBER_OF_PAGES_PURCHASE_TABLE = "noOfPagesPurchaseTable";
    public static final String LIST_USERS = "users";
    public static final String MAP_PURCHASED_FILMS = "purchasedFilms";
    public static final String CURRENT_USERS_PAGE = "currentUsersPage";
    public static final String CURRENT_PURCHASED_FILM_PAGE = "currentPurchasedFilmPage";
    public static final String USERS_ON_PAGE = "usersOnPage";
    public static final String PURCHASED_FILMS_ON_PAGE = "purchasedFilmsOnPage";
    public static final String FILM_ID = "filmId";
    public static final String CURRENT_FILM_NAME = "filmName";
    public static final String CURRENT_FILM_AVATAR = "filmAvatar";
    public static final String CURRENT_DESCRIPTION = "description";
    public static final String CURRENT_YEAR_OF_CREATION = "yearOfCreation";
    public static final String CURRENT_GENRE = "genre";
    public static final String CURRENT_LINK = "link";
    public static final String GENDER = "gender";
    public static final String COUNTRY = "country";
    public static final String ABOUT_ME = "about_me";
    public static final String NAME_USER = "name";
    public static final String AVATAR = "avatar";
    public static final String LANG_CHANGE_PROCESS_COMMAND = "langChangeProcessCommand";
    public static final String CURRENT_FILM_ID = "filmId";
    public static final String PASSWORD = "password";
    public static final String ROLE = "role";
    public static final String CURRENT_PAGE = "currentPage";
    public static final String CURRENT_PAGE_AFTER_REDIRECT = "currentPageAfterRedirect";
    public static final String REDIRECTED_PAGE = "redirectedPage";
    public static final String REPEAT_PASSWORD = "repeat password";
    public static final String LANGUAGE = "language";
    public static final String LANGUAGE_CHANGED = "language_changed";
    public static final String ERROR_DATA = "errorData";
    public static final String ERROR_SEARCH = "errorSearch";
    public static final String INCORRECT_LOGIN_AND_PASSWORD = "errorLoginPassMessage";
    public static final String COMMAND_PROFILE = "profile";
    public static final String USER_IS_LOCKED = "UserIsLocked";
    public static final String REGISTRATION_ERROR = "registrationError";
    public static final String ERROR = "error";
    public static final String COMMAND = "command";
    public static final String CURRENT_NAV_LOCALE = "currentNavLocale";
    public static final String LOCALE_RU = "RU";
    public static final String LOCALE_EN = "EN";
    public static final String UPLOAD_DIR_FOR_USER_AVATAR = "C:\\Kristina\\TaskWebLogin\\src\\main\\webapp\\pictures_for_project\\picturesForAvatar\\";
    public static final String SERVER_UPLOAD_DIR = "C:\\Program Files\\apache-tomcat-8.5.57\\webapps\\TaskWebLogin_war\\pictures_for_project\\picturesForAvatar\\";
    public static final String UPLOAD_RESULT = "upload_result";
    public static final String COMMAND_INIT_START_PAGE = "init_start_page";
    public static final String COMMAND_FORWARD_TO_EDIT_PROFILE = "forward_to_edit_profile";
    public static final String COMMAND_USER_TABLE = "admin_page";
    public static final String COMMAND_PURCHASED_FILM_TABLE = "purchased_film_table";
    public static final String MAKE_ADMIN = "make_admin";
    public static final String INCORRECT_ERROR_SYMBOLS = "registrationErrorSymbols";
    public static final String PASSWORDS_DO_NOT_MATCH = "registrationErrorPasswords";
    public static final String CURRENT_ADMIN_PAGE = "currentAdminsPage";
    public static final String ADMINS_ON_PAGE = "adminsOnPage";
    public static final String LIST_ADMINS = "admins";
    public static final String COMMAND_ADMIN_TABLE = "init_admin_table";
    public static final String MAKE_USER = "make_user";
    public static final String COMMAND_ADMIN_PAGE_FILMS = "admin_page_films";
    public static final String FILM_NAME = "filmName";
    public static final String FILM_NAME_EN = "filmNameEn";
    public static final String COMMAND_FILM = "film";
    public static final String UPLOAD_DIR_FOR_FILM_AVATAR_RU = "C:\\Kristina\\TaskWebLogin\\src\\main\\webapp\\pictures_for_project\\posters_RU\\";
    public static final String UPLOAD_DIR_FOR_FILM_AVATAR_EN = "C:\\Kristina\\TaskWebLogin\\src\\main\\webapp\\pictures_for_project\\posters_EN\\";
    public static final String SERVER_UPLOAD_DIR_FOR_FILM_RU = "C:\\Program Files\\apache-tomcat-8.5.57\\webapps\\TaskWebLogin_war\\pictures_for_project\\posters_RU\\";
    public static final String SERVER_UPLOAD_DIR_FOR_FILM_EN = "C:\\Program Files\\apache-tomcat-8.5.57\\webapps\\TaskWebLogin_war\\pictures_for_project\\posters_EN\\";
    public static final String RU = "ru";
    public static final String EN = "en";
    public static final String CURRENT_FILM_LANG = "currentFilmLang";
    public static final String COMMAND_FORWARD_TO_FILM_EDIT = "forward_to_edit_film";
    public static final String FILM_ACTIVE = "active";
    public static final String COMMAND_VIEW_PURCHASED_FILM = "view_purchased_film";
    public static final String CHOSEN_USER_EMAIL = "chosenUserEmail";
    public static final String COMMAND_VIEW_PROFILE = "view_profile";
    public static final String BUY_FILM = "buyFilm";
    public static final String JUST_BOUGHT = "justBought";
    public static final String FLAG_FOR_BUTTON_TRUE = "true";
    public static final String FLAG_FOR_BUTTON_FALSE = "false";
    public static final String SEARCH_CONTENT = "searchContent";
    public static final String SEARCH_REQUEST = "searchRequest";
    public static final String COMMAND_SEARCH = "search";
    public static final String USER = "user";
    public static final String FILM_EN = "film_en";
    public static final String FILM_RU = "film_ru";
    public static final String ADD_FOR_PATH_AVATAR = "/";
    public static final String LABEL_FOR_FILM_NAME = "Label.FilmName";
    public static final String LABEL_FOR_FILM_DESCRIPTION = "Film.Description";
    public static final String LABEL_FOR_FILM_GENRE = "Film.genre";
    public static final String LABEL_FOR_FILM_LINK = "Film.link";
    public static final String LABEL_FOR_FILM_YEAR_OF_CREATION = "Film.YearOfCreation";
    public static final String LABEL_FOR_FILM_FIELD = "field";
    public static final String COMMAND_VIEW_FILM_PAGE = "view_film_page";
    public static final String ERROR_DATA_FILM_EXISTS = "errorDataExistsFilm";
    public static final String ERROR_MESSAGE_FOR_EDIT_FILM = "Unsuccessful attempt to update movie information";
    public static final String ERROR_MESSAGE_404 = "Page not found";
    public static final String ERROR_MESSAGE_FOR_CREATE_FILM = "Unsuccessful attempt to create a movie";
    public static final String BACK_BUTTON_PAGE_ADDRESS = "backButtonPageAddress";
    public static final String CARD_BACK_BUTTON_PAGE_ADDRESS = "cardBackButtonPageAddress";
    public static final String ERROR_MESSAGE_FOR_BUY_FILM = "Unsuccessful attempt to buy a movie";

    private RequestAttribute() {
    }
}
